### ISSUE TITLE
Output campi numerici

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#1]
se nella query sparql si seleziona una dataproperty mappata con un campo double sul database, se il valore supera una determinata soglia, il valore restituito è in formato esponenziale.

- versione Mastro: mws-1.1.2.war
- sorgente dati Cloudera CDH
- driver jdbc: ImpalaJDBC41.jar
- endpoint utilizzati: /mws/rest/ep/sparql

**Comment by giacomoronconiobda** [comment]
Il formato dell'output può essere parsato in javascript e formattato da Questio tramite la funzione built in [parseFloat](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/parseFloat). La precisione del numero non viene inficiata da questa formattazione finchè le cifre del double sono meno di 17.
