### ISSUE TITLE
Errore query con funzioni di aggregazione

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#21]
Utilizzando la versione Mastro 1.4.0 connesso con Cloudera Impala (libreria ImpalaJDBC42.jar) le query con funzione di aggregazione restituiscono un errore.

Query di esempio:
[ErroreQueryAggregata.sparql.txt](https://github.com/obdasystems/monolith-releases/files/6405825/ErroreQueryAggregata.sparql.txt)

Lo stacktrace dell'errore:
[ErroreQueryAggregata.txt](https://github.com/obdasystems/monolith-releases/files/6405814/ErroreQueryAggregata.txt)

la Mastro Home utilizzata
[mastro-home.zip](https://github.com/obdasystems/monolith-releases/files/6405794/mastro-home.zip)

**Comment by giacomoronconiobda** [comment]
Risolta scaricando il driver JDBC aggiornato IMPALA 2.6.23
