### ISSUE TITLE
Errore Query

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#26]
Si segnala l'errore nella query riportata in allegato.

Query in errore:
[Errore_Filtro.sparql.txt](https://github.com/obdasystems/monolith-releases/files/6432799/Errore_Filtro.sparql.txt)

Lo stacktrace dell'errore:
[Errore_Filtro.errore.txt](https://github.com/obdasystems/monolith-releases/files/6432801/Errore_Filtro.errore.txt)

Fare riferimento alla mastro home riportata nel ticket #21

Versione Mastro: 1.4.1
Sorgente: Cloudera (JDBC IMPALA 2.6.23)

il medesimo costrutto, in modalità CQ (senza funzione di aggregazione) risulta funzionante.

**Comment by valeriosantarelli** [comment]
Buongiorno Francesco, nella Mastro Home allegata ci sono diverse versioni di ontologia e mapping, potresti indicarci quali utilizzare per replicare l'errore?
Grazie

**Comment by fpiergia** [comment]
Buongiorno Valerio,

i riferimenti alla versione dell'ontologia e mapping sono:
-     "ontologyName": "INAIL",
-     "ontologyVersion": "http://okms.inail/ontology/7.3"
-     "mappingID": "inail_impala_7_3_1",
-     "datasourceID": "ClouderaDB"

**Comment by fpiergia** [comment]
In allegato Ontologia e mapping utilizzati per replicare l'errore
[Ontologia_Mapping.zip](https://github.com/obdasystems/monolith-releases/files/6436185/Ontologia_Mapping.zip)

**Comment by NonnonePalmiro** [comment]
Buongiorno Francesco, abbiamo risolto la problematica quindi appena possibile Giacomo ti farà avere il nuovo build di monolith. 
Come unica nota ti segnalerei che, sulla specifica fornita, la query SPARQL risulta essere intensionalmente vuota, quindi l'SQL prodotto ritorna sempre un insieme vuoto di risultati.

Resto a disposizione per chiarimenti, un saluto
