### ISSUE TITLE
Eccezione nell'esecuzione della query

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#3]
Eseguendo la query allegata si riscontra l'eccezione allegata

versione Mastro: mws-1.1.2.war
sorgente dati Cloudera CDH
driver jdbc: ImpalaJDBC41.jar
endpoint utilizzato: /mws/rest/ep/sparql

[sparqlEccezione.txt](https://github.com/obdasystems/monolith-releases/files/5694290/sparqlEccezione.txt)
[logQueryMastro.txt](https://github.com/obdasystems/monolith-releases/files/5694285/logQueryMastro.txt)

**Comment by giacomoronconiobda** [comment]
L'errore sembra dovuto a una o più inconsistenze nei mapping. Si sta cercando di fare un join tra una stringa e un double. Le colonne in gioco sono specificate nell'errore.
```
ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: operands of type STRING and DOUBLE are not comparable: V_00807_1.s_cod_tipo_rendita = V_00763_3.n_cod_tipo_prest_econ
```

**Comment by giacomoronconiobda** [comment]
In particolare credo il problema sia il mapping di `INAIL:renditaHaTipoPrestazioneEconomica` in cui il range ha per template:
```
http://okms.inail/ontology/TipoPrestazioneEconomica/N_COD_TIPO_PREST_ECON={s_cod_tipo_rendita}
```
mentre il mapping di `INAIL:TipoPrestazioneEconomica`
ha per template:
```
http://okms.inail/ontology/TipoPrestazioneEconomica/N_COD_TIPO_PREST_ECON={n_cod_tipo_prest_econ}
```
