### ISSUE TITLE
Modifica Endpoint download CSV

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#4]
Si richiede di modificare l'endpoint dedicato al download in CSV dei risultati di una Query sparql.
Si richiede di crearne uno nuovo come l'attuale (in POST con la query nel Body) ma che non applichi logiche sull' header "Accept".

versione Mastro: mws-1.1.2.war
sorgente dati Cloudera CDH
driver jdbc: ImpalaJDBC41.jar
endpoint utilizzato: /mws/rest/ep/sparql (Accept: application/csv)

**Comment by giacomoronconiobda** [comment]
propongo un path tipo:
```
/mws/rest/ep/sparql/csv
```

**Comment by fpiergia** [comment]
Il path proposto va bene.
Grazie
