### ISSUE TITLE
Puntamenti ad ambiente INAIL

### ISSUE THREAD

**Issue by fpiergia** [obdasystems/monolith-releases#5]
i parametri riportati nel file WEB-INF\web.xml

- jwt.claims.valid_audience
- jwt.jwks_CA

dovrebbero essere esternalizzati dal WAR rilasciato, in quanto dipendono dall'ambiente di deploy (avranno valori diversi in ambiente di certificazione e produzione).

potrebbero essere inclusi, come i datasources nella mastro-home.

Grazie,
Francesco

**Comment by roodsey** [comment]
Modificata la procedura di inizializzazione di MWS in modo che i parametri JWT vengano caricati dal file `mastro.jwt` collocato nella directory $MASTRO_HOME. Il file va strutturato come segue:
```
{
	"jwt.claims.valid_audience" : "collportale.inail.it",
	"jwt.authorities" : "",
	"jwt.jwks_CA" : "https://collportale.inail.it/api/GetCA",
	"jwt.claims.valid-issuer" : "www.inail.it"
}
```
Nel caso in cui il file non sia presente, i valori dei parametri JWT vengono ricercati come avviene ora nel file `web.xml` dell'applicativo deployato
